name: build

on:
  push:
    branches: main
    paths:
      - "!**.md"
      - ".github/workflows/build.yml"
      - "packages/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm build-base
      - run: pnpm lint-base
      - run: pnpm test-base
