name: release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
          scope: "@vanyauhalin"
      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm build-base
      - run: cd packages/stylelint-config-base && pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
